"""add_scanned_emails_table

Revision ID: 335f801d88f8
Revises: 01c8f25b3d41
Create Date: 2026-04-01 23:44:25.712310
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '335f801d88f8'
down_revision: Union[str, None] = '01c8f25b3d41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scanned_emails',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('scan_log_id', sa.Uuid(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('sender_email', sa.String(length=320), nullable=False),
    sa.Column('sender_name', sa.String(length=320), nullable=False),
    sa.Column('recipients_json', sa.Text(), nullable=False),
    sa.Column('body_snippet', sa.Text(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('has_attachments', sa.Boolean(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_actionable', sa.Boolean(), nullable=False),
    sa.Column('analysis_category', sa.String(length=50), nullable=False),
    sa.Column('analysis_confidence', sa.Float(), nullable=False),
    sa.Column('analysis_summary', sa.Text(), nullable=False),
    sa.Column('suggestion_id', sa.Uuid(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scanned_emails_provider_message_id'), 'scanned_emails', ['provider_message_id'], unique=False)
    op.create_index(op.f('ix_scanned_emails_user_id'), 'scanned_emails', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scanned_emails_user_id'), table_name='scanned_emails')
    op.drop_index(op.f('ix_scanned_emails_provider_message_id'), table_name='scanned_emails')
    op.drop_table('scanned_emails')
    # ### end Alembic commands ###
