"""add_drafts_guides_links_onboarding_analytics_tables

Revision ID: a9b8e1f657d6
Revises: 335f801d88f8
Create Date: 2026-04-05 12:56:27.669810
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9b8e1f657d6'
down_revision: Union[str, None] = '335f801d88f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_drafts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider_draft_id', sa.String(length=255), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('original_email_id', sa.String(length=255), nullable=False),
    sa.Column('to_email', sa.String(length=320), nullable=False),
    sa.Column('cc_emails_json', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('proposed_windows_json', sa.Text(), nullable=False),
    sa.Column('pending_invite_json', sa.Text(), nullable=True),
    sa.Column('scheduling_link_id', sa.String(length=64), nullable=True),
    sa.Column('was_sent', sa.Boolean(), nullable=False),
    sa.Column('sent_by_autopilot', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_drafts_status'), 'email_drafts', ['status'], unique=False)
    op.create_index(op.f('ix_email_drafts_thread_id'), 'email_drafts', ['thread_id'], unique=False)
    op.create_index(op.f('ix_email_drafts_user_id'), 'email_drafts', ['user_id'], unique=False)
    op.create_table('onboarding_status',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_status_user_id'), 'onboarding_status', ['user_id'], unique=True)
    op.create_table('pending_invites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('draft_id', sa.Uuid(), nullable=False),
    sa.Column('event_summary', sa.Text(), nullable=False),
    sa.Column('event_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attendees_json', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('calendar_event_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_invites_draft_id'), 'pending_invites', ['draft_id'], unique=False)
    op.create_index(op.f('ix_pending_invites_user_id'), 'pending_invites', ['user_id'], unique=False)
    op.create_table('scheduling_analytics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('draft_id', sa.Uuid(), nullable=True),
    sa.Column('thread_id', sa.String(length=255), nullable=True),
    sa.Column('link_id', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('was_autopilot', sa.Boolean(), nullable=False),
    sa.Column('extra_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduling_analytics_event_type'), 'scheduling_analytics', ['event_type'], unique=False)
    op.create_index(op.f('ix_scheduling_analytics_user_id'), 'scheduling_analytics', ['user_id'], unique=False)
    op.create_table('scheduling_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('link_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('attendee_email', sa.String(length=320), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('thread_id', sa.String(length=255), nullable=True),
    sa.Column('suggested_windows_json', sa.Text(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('booked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduling_links_link_id'), 'scheduling_links', ['link_id'], unique=True)
    op.create_index(op.f('ix_scheduling_links_user_id'), 'scheduling_links', ['user_id'], unique=False)
    op.create_table('user_guides',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('guide_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('emails_analyzed', sa.Integer(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_guides_guide_type'), 'user_guides', ['guide_type'], unique=False)
    op.create_index(op.f('ix_user_guides_user_id'), 'user_guides', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_guides_user_id'), table_name='user_guides')
    op.drop_index(op.f('ix_user_guides_guide_type'), table_name='user_guides')
    op.drop_table('user_guides')
    op.drop_index(op.f('ix_scheduling_links_user_id'), table_name='scheduling_links')
    op.drop_index(op.f('ix_scheduling_links_link_id'), table_name='scheduling_links')
    op.drop_table('scheduling_links')
    op.drop_index(op.f('ix_scheduling_analytics_user_id'), table_name='scheduling_analytics')
    op.drop_index(op.f('ix_scheduling_analytics_event_type'), table_name='scheduling_analytics')
    op.drop_table('scheduling_analytics')
    op.drop_index(op.f('ix_pending_invites_user_id'), table_name='pending_invites')
    op.drop_index(op.f('ix_pending_invites_draft_id'), table_name='pending_invites')
    op.drop_table('pending_invites')
    op.drop_index(op.f('ix_onboarding_status_user_id'), table_name='onboarding_status')
    op.drop_table('onboarding_status')
    op.drop_index(op.f('ix_email_drafts_user_id'), table_name='email_drafts')
    op.drop_index(op.f('ix_email_drafts_thread_id'), table_name='email_drafts')
    op.drop_index(op.f('ix_email_drafts_status'), table_name='email_drafts')
    op.drop_table('email_drafts')
    # ### end Alembic commands ###
