"""add_email_intelligence_tables

Revision ID: aca40b1a2a14
Revises: acbf06ab3ed5
Create Date: 2026-04-01 21:03:37.909311
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aca40b1a2a14'
down_revision: Union[str, None] = 'acbf06ab3ed5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_scan_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('emails_scanned', sa.Integer(), nullable=False),
    sa.Column('actionable_found', sa.Integer(), nullable=False),
    sa.Column('suggestions_created', sa.Integer(), nullable=False),
    sa.Column('errors_json', sa.Text(), nullable=False),
    sa.Column('last_message_id', sa.String(length=255), nullable=True),
    sa.Column('last_message_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_scan_logs_user_id'), 'email_scan_logs', ['user_id'], unique=False)
    op.create_table('schedule_suggestions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=True),
    sa.Column('email_provider_id', sa.String(length=255), nullable=False),
    sa.Column('email_subject', sa.Text(), nullable=False),
    sa.Column('email_sender', sa.String(length=320), nullable=False),
    sa.Column('email_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_snippet', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('proposed_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('proposed_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=False),
    sa.Column('attendees_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('calendar_event_id', sa.String(length=255), nullable=True),
    sa.Column('has_conflict', sa.Boolean(), nullable=False),
    sa.Column('conflict_details', sa.Text(), nullable=False),
    sa.Column('alternative_slots_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_suggestions_org_id'), 'schedule_suggestions', ['org_id'], unique=False)
    op.create_index(op.f('ix_schedule_suggestions_status'), 'schedule_suggestions', ['status'], unique=False)
    op.create_index(op.f('ix_schedule_suggestions_user_id'), 'schedule_suggestions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_suggestions_user_id'), table_name='schedule_suggestions')
    op.drop_index(op.f('ix_schedule_suggestions_status'), table_name='schedule_suggestions')
    op.drop_index(op.f('ix_schedule_suggestions_org_id'), table_name='schedule_suggestions')
    op.drop_table('schedule_suggestions')
    op.drop_index(op.f('ix_email_scan_logs_user_id'), table_name='email_scan_logs')
    op.drop_table('email_scan_logs')
    # ### end Alembic commands ###
