"""add_config_settings_table

Revision ID: acbf06ab3ed5
Revises: 3e777f80443c
Create Date: 2026-03-31 22:44:29.515019
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acbf06ab3ed5'
down_revision: Union[str, None] = '3e777f80443c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_settings_key'), 'config_settings', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_config_settings_key'), table_name='config_settings')
    op.drop_table('config_settings')
    # ### end Alembic commands ###
