"""add_user_scheduling_preferences_columns

Revision ID: e2a317726f0c
Revises: a9b8e1f657d6
Create Date: 2026-04-05 14:02:26.934049
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e2a317726f0c"
down_revision: Union[str, None] = "a9b8e1f657d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "autopilot_enabled", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "email_draft_enabled",
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
    )
    op.add_column(
        "users",
        sa.Column("scheduling_calendar_id", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "users",
        sa.Column(
            "onboarding_completed",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "scheduling_guide_generated",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "style_guide_generated",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "style_guide_generated")
    op.drop_column("users", "scheduling_guide_generated")
    op.drop_column("users", "onboarding_completed")
    op.drop_column("users", "scheduling_calendar_id")
    op.drop_column("users", "email_draft_enabled")
    op.drop_column("users", "autopilot_enabled")
    # ### end Alembic commands ###
